/*
 * onfonmediasmsgateway_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package group_pkg

import "onfonmediasmsgateway_lib/configuration_pkg"

/*
 * Interface for the GROUP_IMPL
 */
type GROUP interface {
    GetGroupList () (interface{}, error)

    CreateNewGroup (string) (interface{}, error)

    UpdateGroup (string, string) (interface{}, error)

    CreateSubGroupGroup (string, string) (interface{}, error)

    DeleteGroup (int64) (interface{}, error)
}

/*
 * Factory for the GROUP interaface returning GROUP_IMPL
 */
func NewGROUP(config configuration_pkg.CONFIGURATION) *GROUP_IMPL {
    client := new(GROUP_IMPL)
    client.config = config
    return client
}