/*
 * onfonmediasmsgateway_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package configuration_pkg



type CONFIGURATION interface {
        AccessKey() string
        SetAccessKey(accessKey   string)
        ApiKey() string
        SetApiKey(apiKey   string)
        ClientId() string
        SetClientId(clientId   string)
}

/*
 * Factory for the CONFIGURATION interface returning CONFIGURATION_IMPL
 */
func NewCONFIGURATION() CONFIGURATION{
    configuration := new(CONFIGURATION_IMPL)
    return configuration
}