/*
 * onfonmediasmsgateway_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package OnfonMediaSMSGatewayClient

import(
	"onfonmediasmsgateway_lib/configuration_pkg"
	"onfonmediasmsgateway_lib/account_pkg"
	"onfonmediasmsgateway_lib/template_pkg"
	"onfonmediasmsgateway_lib/sms_pkg"
	"onfonmediasmsgateway_lib/group_pkg"
	"onfonmediasmsgateway_lib/campaign_pkg"
)


/*
 * Interface for the ONFONMEDIASMSGATEWAY_IMPL
 */
type ONFONMEDIASMSGATEWAY interface {
    Account()               account_pkg.ACCOUNT
    Template()              template_pkg.TEMPLATE
    SMS()                   sms_pkg.SMS
    GROUP()                 group_pkg.GROUP
    Campaign()              campaign_pkg.CAMPAIGN
    Configuration()         configuration_pkg.CONFIGURATION
}

/*
 * Factory for the ONFONMEDIASMSGATEWAY interface returning ONFONMEDIASMSGATEWAY_IMPL
 */
func NewONFONMEDIASMSGATEWAY() ONFONMEDIASMSGATEWAY {
    onfonMediaSMSGatewayClient := new(ONFONMEDIASMSGATEWAY_IMPL)
    onfonMediaSMSGatewayClient.config = configuration_pkg.NewCONFIGURATION()

    return onfonMediaSMSGatewayClient
}
